### ISSUE TITLE
Scroll bar or multiple notification simultaneous

### ISSUE THREAD

**Issue by kj020** [LiorBanai/Notification-Popup-Window#21]
Is there any support for multiple notifications or a scroll bar, e.g., if there is an if and else if statement both notification are shown either on top of each other or vertically.
When there is more than 5 item u cant see the sixth a scroll bar would solve this issue.
Do u think there is any way to implement these features?
Thanks in advance.

**Comment by LiorBanai** [comment]
Hi, it does support multiple pop-ups. They are stacked one above the others when more than one are shown

**Comment by LiorBanai** [comment]
Hi @kj020 , it does support multiple pop-ups. They are stacked one above the others when more than one are shown
e.g:
![image](https://user-images.githubusercontent.com/36262995/103155354-c844e180-47a7-11eb-80af-f128b73590f6.png)

**Comment by kj020** [comment]
What i want to is when i press a button on the form two condition is to be
met with two different notification but when the conditions are met only 1
notification come up.
Ok saw ur other last email.
i think i need to change the variable name of the one of the notification.
Will get back to you.

**Comment by LiorBanai** [comment]
There is example demo project that you can run to see how to show multiple popups. you need to create 2 or more poupups in code and call show on each one.

**Comment by kj020** [comment]
Thanks, I'll check it out.

**Comment by kj020** [comment]
Got it. Thanks 👍

**Comment by LiorBanai** [comment]
Did it work? I'll close this one. Feel free to open new issue if there are other problems or questions.
